//! AIFF and FLAC decode against sample-exact WAV twins, plus format
//! auto-detection and truncation/garbage fuzzing.
//!
//! Fixtures are synthetic, generated by `tests/fixtures/generate.sh`; see
//! `tests/fixtures/MANIFEST.md` for the matrix and provenance.

use phx_audio::{Audio, AudioError};

fn assert_sample_exact(a: &Audio, b: &Audio) {
    assert_eq!(a.channel_count(), b.channel_count());
    assert_eq!(a.frames(), b.frames());
    assert_eq!(a.sample_rate(), b.sample_rate());
    for ch in 0..a.channel_count() {
        let (left, right) = (a.channel(ch), b.channel(ch));
        for (index, (l, r)) in left.iter().zip(right).enumerate() {
            assert_eq!(
                l.to_bits(),
                r.to_bits(),
                "channel {ch} frame {index}: {l} != {r}"
            );
        }
    }
}

macro_rules! aiff_case {
    ($fn_name:ident, $name:literal, $channels:literal) => {
        #[test]
        fn $fn_name() {
            let aiff = include_bytes!(concat!("fixtures/", $name, ".aiff"));
            let wav = include_bytes!(concat!("fixtures/", $name, ".wav"));
            let from_aiff = Audio::from_aiff_bytes(aiff).expect("AIFF fixture must decode");
            let from_wav = Audio::from_wav_bytes(wav).expect("WAV twin must decode");
            assert_eq!(from_aiff.channel_count(), $channels);
            assert_sample_exact(&from_aiff, &from_wav);

            // Auto-detection must route to the same decode path.
            let detected = Audio::from_bytes(aiff).expect("AIFF must auto-detect");
            assert_sample_exact(&detected, &from_wav);
        }
    };
}

aiff_case!(aiff_mono_16_44100, "aiff_mono_16_44100", 1);
aiff_case!(aiff_mono_16_48000, "aiff_mono_16_48000", 1);
aiff_case!(aiff_mono_24_44100, "aiff_mono_24_44100", 1);
aiff_case!(aiff_mono_24_48000, "aiff_mono_24_48000", 1);
aiff_case!(aiff_stereo_16_44100, "aiff_stereo_16_44100", 2);
aiff_case!(aiff_stereo_16_48000, "aiff_stereo_16_48000", 2);
aiff_case!(aiff_stereo_24_44100, "aiff_stereo_24_44100", 2);
aiff_case!(aiff_stereo_24_48000, "aiff_stereo_24_48000", 2);

macro_rules! flac_case {
    ($fn_name:ident, $flac_name:literal, $wav_name:literal, $channels:literal) => {
        #[test]
        fn $fn_name() {
            let flac = include_bytes!(concat!("fixtures/", $flac_name, ".flac"));
            let wav = include_bytes!(concat!("fixtures/", $wav_name, ".wav"));
            let from_flac = Audio::from_flac_bytes(flac).expect("FLAC fixture must decode");
            let from_wav = Audio::from_wav_bytes(wav).expect("WAV twin must decode");
            assert_eq!(from_flac.channel_count(), $channels);
            assert_sample_exact(&from_flac, &from_wav);

            let detected = Audio::from_bytes(flac).expect("FLAC must auto-detect");
            assert_sample_exact(&detected, &from_wav);
        }
    };
}

flac_case!(flac_compression_level_0, "flac_level0", "flac_base16", 2);
flac_case!(flac_compression_level_5, "flac_level5", "flac_base16", 2);
flac_case!(flac_compression_level_8, "flac_level8", "flac_base16", 2);
flac_case!(
    flac_non_standard_block_size,
    "flac_blocksize",
    "flac_base16",
    2
);
flac_case!(flac_24_bit_mono, "flac_24bit", "flac_base24", 1);

#[test]
fn flac_compression_levels_agree_with_each_other_bit_for_bit() {
    // Every compression-level/block-size fixture is a lossless re-encode of
    // the same PCM; cross-checking them against each other (not just against
    // the WAV twin) rules out a bug that happens to match the twin by luck.
    let level0 = Audio::from_flac_bytes(include_bytes!("fixtures/flac_level0.flac")).unwrap();
    let level8 = Audio::from_flac_bytes(include_bytes!("fixtures/flac_level8.flac")).unwrap();
    let blocksize = Audio::from_flac_bytes(include_bytes!("fixtures/flac_blocksize.flac")).unwrap();
    assert_sample_exact(&level0, &level8);
    assert_sample_exact(&level0, &blocksize);
}

#[test]
fn format_auto_detection_rejects_unrecognized_bytes() {
    let err = Audio::from_bytes(b"not an audio file at all").unwrap_err();
    assert_eq!(err, AudioError::UnrecognizedFormat);
}

#[test]
fn format_auto_detection_handles_short_and_empty_input_without_panicking() {
    assert_eq!(
        Audio::from_bytes(b"").unwrap_err(),
        AudioError::UnrecognizedFormat
    );
    assert_eq!(
        Audio::from_bytes(b"FORM").unwrap_err(),
        AudioError::UnrecognizedFormat
    );
    assert_eq!(
        Audio::from_bytes(b"RIFF").unwrap_err(),
        AudioError::UnrecognizedFormat
    );
}

#[test]
fn truncated_aiff_is_a_typed_error_not_a_panic() {
    let full = include_bytes!("fixtures/aiff_stereo_24_48000.aiff");
    for cut in [1, 4, 12, 20, 40, 100, full.len() / 2, full.len() - 1] {
        let truncated = &full[..full.len() - cut];
        match Audio::from_aiff_bytes(truncated) {
            Ok(audio) => {
                // A truncated SSND chunk can still leave a decodable, shorter
                // stream; that is fine as long as it is not longer than the
                // source and every sample is finite.
                assert!(audio.frames() <= 48_000 * 3 / 10);
                for ch in 0..audio.channel_count() {
                    assert!(audio.channel(ch).iter().all(|s| s.is_finite()));
                }
            }
            Err(err) => {
                assert!(matches!(
                    err,
                    AudioError::MalformedAiff(_) | AudioError::UnsupportedAiff { .. }
                ));
            }
        }
    }
}

#[test]
fn truncated_flac_is_a_typed_error_not_a_panic() {
    let full = include_bytes!("fixtures/flac_level8.flac");
    for cut in [1, 4, 12, 20, 100, full.len() / 2, full.len() - 1] {
        let truncated = &full[..full.len() - cut];
        match Audio::from_flac_bytes(truncated) {
            Ok(audio) => {
                assert!(audio.frames() <= 44_100 * 3 / 10);
                for ch in 0..audio.channel_count() {
                    assert!(audio.channel(ch).iter().all(|s| s.is_finite()));
                }
            }
            Err(err) => {
                assert!(matches!(
                    err,
                    AudioError::MalformedFlac(_) | AudioError::UnsupportedFlac { .. }
                ));
            }
        }
    }
}

#[test]
fn garbage_bytes_are_typed_errors_for_every_decode_entry_point_not_a_panic() {
    let patterns: &[&[u8]] = &[
        &[],
        &[0u8],
        &[0xffu8; 16],
        &[0x00u8; 64],
        b"FORM\x00\x00\x00\x00AIFFxxxxxxxxxxxxxxxxxxxx",
        b"fLaC\x00\x00\x00\x00garbage garbage garbage",
        b"RIFF\x00\x00\x00\x00WAVEgarbagegarbagegarbage",
    ];
    for pattern in patterns {
        assert!(Audio::from_aiff_bytes(pattern).is_err());
        assert!(Audio::from_flac_bytes(pattern).is_err());
        // from_bytes must never panic either, whether or not it recognizes
        // the leading signature.
        let _ = Audio::from_bytes(pattern);
    }
}

#[test]
fn random_fuzz_bytes_never_panic_any_decode_entry_point() {
    // Deterministic xorshift, no external RNG dependency.
    let mut state: u64 = 0x9E3779B97F4A7C15;
    let mut next = || {
        state ^= state << 13;
        state ^= state >> 7;
        state ^= state << 17;
        state
    };

    for trial in 0..200u32 {
        let len = (next() % 512) as usize;
        let mut bytes = vec![0u8; len];
        for byte in &mut bytes {
            *byte = (next() & 0xff) as u8;
        }
        // Bias some trials toward a real magic prefix so the parser gets
        // further into the format before hitting garbage.
        if trial % 4 == 0 && bytes.len() >= 12 {
            bytes[0..4].copy_from_slice(b"FORM");
            bytes[8..12].copy_from_slice(b"AIFF");
        } else if trial % 4 == 1 && bytes.len() >= 4 {
            bytes[0..4].copy_from_slice(b"fLaC");
        }

        let _ = Audio::from_aiff_bytes(&bytes);
        let _ = Audio::from_flac_bytes(&bytes);
        let _ = Audio::from_bytes(&bytes);
    }
}
