#!/usr/bin/env bash
# Regenerates the AIFF/FLAC decode fixtures from scratch.
#
# Every fixture is synthetic (two sine tones, distinct per channel so a
# channel-order bug shows up), generated by `ffmpeg` (WAV/AIFF) and the
# reference `flac` encoder (FLAC). Each AIFF fixture has a WAV twin encoding
# the identical PCM samples (mono/stereo source, then repacked big-endian);
# every FLAC fixture at every compression level and block size shares one WAV
# twin per bit depth, since FLAC is lossless and must decode back to the same
# samples regardless of how it was compressed.
set -euo pipefail
cd "$(dirname "$0")"

duration=0.3

gen_wav_mono() {
  local rate=$1 bits=$2 out=$3
  ffmpeg -y -loglevel error -f lavfi -i "sine=frequency=440:sample_rate=${rate}:duration=${duration}" \
    -map_metadata -1 -c:a "pcm_s${bits}le" -ar "${rate}" -ac 1 "${out}"
}

gen_wav_stereo() {
  local rate=$1 bits=$2 out=$3
  ffmpeg -y -loglevel error \
    -f lavfi -i "sine=frequency=440:sample_rate=${rate}:duration=${duration}" \
    -f lavfi -i "sine=frequency=660:sample_rate=${rate}:duration=${duration}" \
    -filter_complex "amerge=inputs=2" -map_metadata -1 -c:a "pcm_s${bits}le" -ar "${rate}" -ac 2 "${out}"
}

for rate in 44100 48000; do
  for bits in 16 24; do
    for ch in mono stereo; do
      name="aiff_${ch}_${bits}_${rate}"
      if [ "$ch" = "mono" ]; then
        gen_wav_mono "$rate" "$bits" "${name}.wav"
      else
        gen_wav_stereo "$rate" "$bits" "${name}.wav"
      fi
      ffmpeg -y -loglevel error -i "${name}.wav" -map_metadata -1 -c:a "pcm_s${bits}be" "${name}.aiff"
    done
  done
done

# FLAC: 16-bit stereo 44.1 kHz source at three compression levels plus one
# fixture with a non-default block size (1152 samples vs. the 4096 default).
gen_wav_stereo 44100 16 flac_base16.wav
flac -f -s -0 -o flac_level0.flac flac_base16.wav
flac -f -s -5 -o flac_level5.flac flac_base16.wav
flac -f -s -8 -o flac_level8.flac flac_base16.wav
flac -f -s --blocksize=1152 -8 -o flac_blocksize.flac flac_base16.wav

# FLAC: 24-bit mono 48 kHz source, exercising the wider bit depth.
gen_wav_mono 48000 24 flac_base24.wav
flac -f -s -6 -o flac_24bit.flac flac_base24.wav

echo "fixtures regenerated in $(pwd)"
