import type {
  AnnotationId,
  AppliedChange,
  AudioId,
  AudioInfo,
  BoundaryId,
  CoreClientLike,
  FigureExportFormat,
  FigureExportResult,
  FigureSidecar,
  FigureSpec,
  FormantTrackData,
  IntensityTrackData,
  IntervalData,
  IntervalId,
  LabelHit,
  LoadedProjectContainer,
  LoadedProjectMedia,
  MinMaxPyramidSlice,
  PitchTrackData,
  PointData,
  PointId,
  ProjectSummary,
  RecordingEntry,
  SaveProjectMediaSpec,
  SaveProjectSpec,
  Selection,
  SelectionReadout,
  SpectrogramTileRequest,
  TierId,
  TierInfo,
  VoiceReportData
} from '@phonix/ui';

export type {
  AnnotationId,
  AppliedChange,
  AudioId,
  AudioInfo,
  BoundaryId,
  FigureExportFormat,
  FigureExportResult,
  FigureSidecar,
  FigureSpec,
  FormantTrackData,
  IntensityTrackData,
  IntervalData,
  IntervalId,
  LabelHit,
  LoadedProjectContainer,
  LoadedProjectMedia,
  MinMaxPyramidSlice,
  PitchTrackData,
  PointData,
  PointId,
  ProjectSummary,
  RecordingEntry,
  SaveProjectMediaSpec,
  SaveProjectSpec,
  Selection,
  SelectionReadout,
  SpectrogramTileRequest,
  TierId,
  TierInfo,
  VoiceReportData
};

export type CoreClient = CoreClientLike;
